alurareceita/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("receitas.urls")),
    path("usuarios/", include("usuarios.urls")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

receitas/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from receitas import views

app_name = "receitas"
urlpatterns = [
    path("", views.index, name="index"),
    path("receitas/<int:id_receita>", views.detalhe, name="detalhe"),
    path("receitas/buscar", views.buscar, name="buscar"),
    path(
        "receitas/criar",
        login_required(views.CriaReceita.as_view(), login_url="login"),
        name="criar",
    ),
    path(
        "receitas/editar/<int:id_receita>",
        login_required(views.EditaReceita.as_view(), "login"),
        name="editar",
    ),
    path(
        "receitas/deletar/<int:id_receita>",
        login_required(views.DeletaReceita.as_view(), login_url="login"),
        name="deletar",
    ),
]

handler404 = "receitas.views.error404"

templates/partials/_busca.html
{% load static %}
<!-- Search Wrapper -->
<div class="search-wrapper">
  <!-- Close Btn -->
  <div class="close-btn"><i class="fa fa-times" aria-hidden="true"></i></div>

  <div class="container">
    <div class="row">
      <div class="col-12">
        <form action="{% url 'receitas:buscar' %}">
          {% csrf_token %}
          <input type="search" name="buscar" placeholder="O que está procurando...">
          <button type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
        </form>
      </div>
    </div>
  </div>
</div>

templates/partials/_footer.html
{% load static %}
<!-- ##### Footer Area Start ##### -->
<footer class="footer-area">
  <div class="container h-100">
    <div class="row h-100">
      <div class="col-12 h-100 d-flex flex-wrap align-items-center justify-content-between">
        <!-- Footer Social Info -->
        <div class="footer-social-info text-right">
          <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
          <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
        </div>
        <!-- Footer Logo -->
        <div class="footer-logo">
          <a href="{% url 'receitas:index' %}"><img src="{% static 'img/core-img/logo.png' %}" alt=""></a>
        </div>
      </div>
    </div>
  </div>
</footer>
<!-- ##### Footer Area Start ##### -->

templates/partials/_menu.html
{% load static %}
<!-- ##### Header Area Start ##### -->
<header class="header-area">
  <!-- Top Header Area -->
  <div class="top-header-area">
    <div class="container h-100">
      <div class="row h-100 align-items-center justify-content-between">
        <!-- Breaking News -->
        <div class="col-12 col-sm-6">
          <div class="breaking-news">
            <div id="breakingNewsTicker" class="ticker">
              <ul>
                <li><a href="">Boas vindas!</a></li>
                <li><a href="">As melhores receitas</a></li>
                <li><a href="">Você encontra aqui!</a></li>
              </ul>
            </div>
          </div>
        </div>

        <!-- Top Social Info -->
        <div class="col-12 col-sm-6">
          <div class="top-social-info text-right">
            <a href=""><i class="fa fa-facebook" aria-hidden="true"></i></a>
            <a href=""><i class="fa fa-twitter" aria-hidden="true"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Navbar Area -->
  <div class="delicious-main-menu">
    <div class="classy-nav-container breakpoint-off">
      <div class="container">
        <!-- Menu -->
        <nav class="classy-navbar justify-content-between" id="deliciousNav">
          <!-- Logo -->
          <a class="nav-brand" href="{% url 'receitas:index' %}"><img src="{% static 'img/core-img/logo.png' %}"
              alt="" /></a>

          <!-- Navbar Toggler -->
          <div class="classy-navbar-toggler">
            <span class="navbarToggler"><span></span><span></span><span></span></span>
          </div>

          <!-- Menu -->
          <div class="classy-menu">
            <!-- close btn -->
            <div class="classycloseIcon">
              <div class="cross-wrap">
                <span class="top"></span><span class="bottom"></span>
              </div>
            </div>

            <!-- Nav Start -->
            <div class="classynav">
              <ul>
                {% if user.is_authenticated %}
                <li><a href="{% url 'receitas:index' %}">Home</a></li>
                <li><a href="{% url 'dashboard' %}">Dashboard</a></li>
                <li><a href="{% url 'receitas:criar' %}">Criar receita</a></li>
                <li><a href="{% url 'logout' %}">Sair</a></li>
                {% else %}
                <li><a href="{% url 'receitas:index' %}">Home</a></li>
                <li><a href="{% url 'cadastro' %}">Cadastro</a></li>
                <li><a href="{% url 'login' %}">Login</a></li>
                {% endif %}
              </ul>

              <!-- Formulario de busca -->
              <div class="search-btn">
                <i class="fa fa-search" aria-hidden="true"></i>
              </div>
              <!-- Formulario de busca -->
            </div>
            <!-- Nav End -->
          </div>
        </nav>
      </div>
    </div>
  </div>
</header>
<!-- ##### Header Area End ##### -->

templates/partials/menu.html
{% load static %}
<!-- ##### Header Area Start ##### -->
<header class="header-area">
  <!-- Top Header Area -->
  <div class="top-header-area">
    <div class="container h-100">
      <div class="row h-100 align-items-center justify-content-between">
        <!-- Breaking News -->
        <div class="col-12 col-sm-6">
          <div class="breaking-news">
            <div id="breakingNewsTicker" class="ticker">
              <ul>
                <li><a href="">Boas vindas!</a></li>
                <li><a href="">As melhores receitas</a></li>
                <li><a href="">Você encontra aqui!</a></li>
              </ul>
            </div>
          </div>
        </div>

        <!-- Top Social Info -->
        <div class="col-12 col-sm-6">
          <div class="top-social-info text-right">
            <a href=""><i class="fa fa-facebook" aria-hidden="true"></i></a>
            <a href=""><i class="fa fa-twitter" aria-hidden="true"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Navbar Area -->
  <div class="delicious-main-menu">
    <div class="classy-nav-container breakpoint-off">
      <div class="container">
        <!-- Menu -->
        <nav class="classy-navbar justify-content-between" id="deliciousNav">
          <!-- Logo -->
          <a class="nav-brand" href="{% url 'index' %}"
            ><img src="{% static 'img/core-img/logo.png' %}" alt=""
          /></a>

          <!-- Navbar Toggler -->
          <div class="classy-navbar-toggler">
            <span class="navbarToggler"
              ><span></span><span></span><span></span
            ></span>
          </div>

          <!-- Menu -->
          <div class="classy-menu">
            <!-- close btn -->
            <div class="classycloseIcon">
              <div class="cross-wrap">
                <span class="top"></span><span class="bottom"></span>
              </div>
            </div>

            <!-- Nav Start -->
            <div class="classynav">
              <ul>
                {% if user.is_authenticated %}
                <li><a href="{% url 'index' %}">Home</a></li>
                <li><a href="{% url 'dashboard' %}">Dashboard</a></li>
                <li><a href="{% url 'cria.receita' %}">Criar receita</a></li>
                <li><a href="{% url 'logout' %}">Sair</a></li>
                {% else %}
                <li><a href="{% url 'index' %}">Home</a></li>
                <li><a href="{% url 'cadastro' %}">Cadastro</a></li>
                <li><a href="{% url 'login' %}">Login</a></li>
                {% endif %}
              </ul>

              <!-- Formulario de busca -->
              <div class="search-btn">
                <i class="fa fa-search" aria-hidden="true"></i>
              </div>
              <!-- Formulario de busca -->
            </div>
            <!-- Nav End -->
          </div>
        </nav>
      </div>
    </div>
  </div>
</header>
<!-- ##### Header Area End ##### -->