alurareceita/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("receitas.urls")),
    path("usuarios/", include("usuarios.urls")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

receitas/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from receitas import views

app_name = "receitas"
urlpatterns = [
    path("", views.index, name="index"),
    path("receitas/<int:id_receita>", views.detalhe, name="detalhe"),
    path("receitas/buscar", views.buscar, name="buscar"),
    path(
        "receitas/criar",
        login_required(views.CriaReceita.as_view(), login_url="login"),
        name="criar",
    ),
    path(
        "receitas/editar/<int:id_receita>",
        login_required(views.EditaReceita.as_view(), "login"),
        name="editar",
    ),
    path(
        "receitas/deletar/<int:id_receita>",
        login_required(views.DeletaReceita.as_view(), login_url="login"),
        name="deletar",
    ),
]

handler404 = "receitas.views.error404"

usuarios/urls.py
from django.urls import path

from usuarios import views

urlpatterns = [
    path("cadastro", views.cadastro, name="cadastro"),
    path("login", views.LoginView.as_view(), name="login"),
    path("dashboard", views.dashboard, name="dashboard"),
    path("logout", views.logout, name="logout"),
]

usuarios/models.py
from django.db import models

# Create your models here.

usuarios/views.py
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View

from receitas.models import Receita


# TODO: Trocar todos os prints por messages do django.
def cadastro(request):
    if request.method == "POST":
        nome = request.POST["nome"]
        email = request.POST["email"]
        senha = request.POST["password"]
        confirmacao_senha = request.POST["password2"]

        if not nome.strip():
            print("Nome inválido")
            return redirect("cadastro")

        if not email.strip():
            print("E-mail inválido")
            return redirect("cadastro")

        if not senha.strip():
            print("Senha inválida")
            return redirect("cadastro")

        if not confirmacao_senha.strip() and confirmacao_senha.strip() != senha.strip():
            print("Senha de confirmacao está incorreta")
            return redirect("cadastro")

        if User.objects.filter(email=email).exists():
            return redirect("cadastro")

        user = User.objects.create_user(username=nome, email=email, password=senha)
        user.save()

        return redirect("login")
    return render(request, "usuarios/cadastro.html")


class LoginView(View):
    def get(self, request):
        return render(request, "usuarios/login.html")

    def post(self, request):
        email: str = request.POST["email"]
        senha: str = request.POST["senha"]

        try:
            user = get_object_or_404(User, email=email)
            user = auth.authenticate(request, username=user.username, password=senha)
            if user is not None:
                auth.login(request, user)
                return redirect("dashboard")
            else:
                messages.add_message(
                    request, messages.ERROR, "Usuário ou senha incorretos!"
                )
                return redirect(to="login")
        except Http404:
            messages.add_message(
                request, messages.ERROR, "Usuário ou senha incorretos!"
            )
            return redirect(to="login")


@login_required(login_url="login")
def dashboard(request):
    receitas = Receita.objects.filter(pessoa=request.user.id).order_by("-data_receita")
    paginator = Paginator(receitas, 10)
    page = request.GET.get("page")
    receitas_por_pagina = paginator.get_page(page)
    return render(request, "usuarios/dashboard.html", {"receitas": receitas_por_pagina})


def logout(request):
    if request.user.is_authenticated:
        auth.logout(request)
        return redirect(to="index")
    return redirect(to="index")

templates/usuarios/cadastro.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Preloader -->
<div id="preloader">
  <i class="circle-preloader"></i>
  <img src="{% static 'img/core-img/pizza.png' %}" alt="">
</div>

{% include 'partials/_busca.html' %}

{% include 'partials/_menu.html' %}

<!-- ##### Contact Form Area Start ##### -->
<div class="contact-area section-padding-0-80">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="section-heading">
          <h2>Criar conta</h2>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-12">
        <div class="contact-form-area">
          <form action="{% url 'cadastro' %}" method="POST">
            {% csrf_token %}
            <div class="row">
              <div class="col-12 col-lg-12">
                <label for="nome_receita"><b>Nome completo</b></label>
                <input type="text" class="form-control" name="nome" placeholder="Ex.:Guilherme Lima" required>
              </div>
              <div class="col-12 col-lg-12">
                <label for="email"><b>Email</b></label>
                <input type="email" class="form-control" name="email" placeholder="Ex.: guilherme@receitas.com"
                  required>
              </div>
              <div class="col-12 col-lg-6">
                <label for="password"><b>Senha</b></label>
                <input type="password" class="form-control" name="password" placeholder="Digite sua senha" required>
              </div>
              <div class="col-12 col-lg-6">
                <label for="password2"><b>Confirmação de senha</b></label>
                <input type="password" class="form-control" name="password2" placeholder="Digite sua senha mais uma vez"
                  required>
              </div>
              <div class="col-12 text-center">
                <button class="btn btn-success" type="submit">Criar sua conta</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% include 'partials/_footer.html' %}
{% endblock %}

templates/usuarios/cria_receita.html
{% extends 'base.html' %} {% load static %} {% block content %}

<!-- Exibe as mensagens -->
{% if messages %} {% for message in messages %}
<div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
{% endfor %} {% endif %}

<!-- Preloader -->
<div id="preloader">
  <i class="circle-preloader"></i>
  <img src="{% static 'img/core-img/pizza.png' %}" alt="" />
</div>

{% include 'partials/_busca.html' %} {% include 'partials/_menu.html' %}

<!-- ##### Contact Form Area Start ##### -->
<div class="contact-area section-padding-0-80">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="section-heading">
          <h3>Crie sua receita, {{ user.username }} :)</h3>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-12">
        <p>Todos os campos são obrigatórios</p>
        <div class="contact-form-area">
          <form action="{% url 'cria.receita' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
              <div class="col-12 col-lg-12">
                <label for="nome_receita"><b>Título da receita</b></label>
                <input type="text" id="nome_receita" class="form-control" name="nome_receita"
                  placeholder="Ex. Suco de limão" required />
              </div>
              <div class="col-12">
                <label for="file"><b>Ingredientes</b></label>
                <textarea class="form-control" name="ingredientes" cols="30" rows="10"
                  placeholder="Ex. 2 Limões &#10;200ml de água" required></textarea>
              </div>
              <div class="col-12">
                <label for="file"><b>Modo de preparo</b></label>
                <textarea class="form-control" name="modo_preparo" cols="30" rows="10"
                  placeholder="Ex. Corte o limão com cuidado e exprema no copo  &#10;Misture com a água e sirva."
                  required></textarea>
              </div>
              <div class="col-12 col-lg-3">
                <label for="file"><b>Tempo de preparo (minutos)</b></label>
                <input type="number" class="form-control" name="tempo_preparo" placeholder="Ex. 2" required />
              </div>
              <div class="col-12 col-lg-3">
                <label for="file"><b>Rendimento</b></label>
                <input type="text" class="form-control" name="rendimento" placeholder="Ex. serve 1 pessoa" required />
              </div>
              <div class="col-12 col-lg-3">
                <label for="file"><b>Categoria da receita</b></label>
                <input type="text" class="form-control" name="categoria" placeholder="Ex. Sucos e bebidas" required />
              </div>
              <div class="col-12 col-lg-3">
                <label for="file"><b>Foto</b></label>
                <input type="file" class="form-control" name="foto_receita" required />
              </div>
              <div class="col-12 text-center">
                <button class="btn delicious-btn mt-30" type="submit">
                  Criar sua receita
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% include 'partials/_footer.html' %} {% endblock %}

templates/usuarios/dashboard.html
{% extends 'base.html' %} {% load static %} {% block content %}
<!-- Preloader -->
<div id="preloader">
  <i class="circle-preloader"></i>
  <img src="{% static 'img/core-img/pizza.png' %}" alt="" />
</div>

{% include 'partials/_busca.html' %} {% include 'partials/_menu.html' %}

<div class="contact-area section-padding-0-80">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="section-heading">
          <h3>Olá {{ user.username }}</h3>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- ##### Best Receipe Area Start ##### -->
<section class="best-receipe-area">
  <div class="container">
    {% if messages %} {% for message in messages %}
    <div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
    {% endfor %} {% endif %}
    <div class="row">
      {% if receitas %} {% for receita in receitas %}
      <!-- Single Best Receipe Area -->
      <div class="col-12 col-sm-6 col-lg-4">
        <div class="single-best-receipe-area mb-30">
          {% if not receita.foto_receita %}
          <img src="{% static 'img/bg-img/foto_receita.png' %}" alt="" />
          {% else %}
          <img src="{{ receita.foto_receita.url }}" alt="" />
          {% endif %}
          <div class="receipe-content">
            <a href="{% url 'receitas:detalhe' receita.id %}">
              <h5>{{receita.nome_receita}}</h5>
            </a>
            <a class="btn btn-warning" role="button" href="{% url 'receitas:editar' receita.id %}">Editar</a>
            <a class="btn btn-danger" role="button" href="{% url 'receitas:deletar' receita.id %}">Deletar</a>
          </div>
        </div>
      </div>
      {% endfor %} {% else %}
      <div class="col-12 col-sm-6 col-lg-4">
        <p>Nenhuma receita encontrada</p>
      </div>
      {% endif %}
    </div>
  </div>
</section>
<!-- ##### Best Receipe Area End ##### -->
<!-- ##### Pagination ##### -->
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {% if receitas.has_other_pages %}
    {% if receitas.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ receitas.previous_page_number }}"><span aria-hidden="true">&laquo;</span></a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="?page={{ page. }}"> <span aria-hidden="true">&laquo;</span> </a>
    </li>
    {% endif %}

    {% for page in receitas.paginator.page_range %}
    {% if page == receitas.number %}
    <li class="page-item active">
      <a class="page-link" href="?page={{ page }}">{{ page }}</a>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page }}">{{ page }}</a>
    </li>
    {% endif %}
    {% endfor %}

    {% if not receitas.has_next %}
    <li class="page-item disabled">
      <a class="page-link"><span aria-hidden="true">&raquo;</span></a>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ receitas.next_page_number }}"> <span aria-hidden="true">&raquo;</span> </a>
    </li>
    {% endif %}
    {% endif %}
  </ul>
</nav>
<!-- ##### Pagination End ##### -->
{% include 'partials/_footer.html' %} {% endblock %}

templates/usuarios/editar_receita.html
{% extends 'base.html' %} {% load static %} {% block content %}

<!-- Exibe as mensagens -->
{% if messages %} {% for message in messages %}
<div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
{% endfor %} {% endif %}

<!-- Preloader -->
<div id="preloader">
  <i class="circle-preloader"></i>
  <img src="{% static 'img/core-img/pizza.png' %}" alt="" />
</div>

{% include 'partials/_busca.html' %} {% include 'partials/_menu.html' %}

<!-- ##### Contact Form Area Start ##### -->
<div class="contact-area section-padding-0-80">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="section-heading">
          <h3>Edite sua receita, {{ user.username }} :)</h3>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-12">
        <p>Todos os campos são obrigatórios</p>
        <div class="contact-form-area">
          <form action="{% url 'editar' receita.id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
              <div class="col-12 col-lg-12">
                <label for="nome_receita"><b>Título da receita</b></label>
                <input type="text" id="nome_receita" class="form-control" name="nome_receita"
                  placeholder="Ex. Suco de limão" value="{{ receita.nome_receita }}" required />
              </div>
              <div class="col-12">
                <label for="file"><b>Ingredientes</b></label>
                <textarea class="form-control" name="ingredientes" cols="30" rows="10"
                  placeholder="Ex. 2 Limões &#10;200ml de água" required>{{ receita.ingredientes }} </textarea>
              </div>
              <div class="col-12">
                <label for="file"><b>Modo de preparo</b></label>
                <textarea class="form-control" name="modo_preparo" cols="30" rows="10"
                  placeholder="Ex. Corte o limão com cuidado e exprema no copo  &#10;Misture com a água e sirva."
                  required>{{ receita.modo_preparo }}
              </textarea>
              </div>
              <div class="col-12 col-lg-3">
                <label for="file"><b>Tempo de preparo (minutos)</b></label>
                <input type="number" class="form-control" name="tempo_preparo" placeholder="Ex. 2"
                  value="{{ receita.tempo_preparo }}" required />
              </div>
              <div class="col-12 col-lg-3">
                <label for="file"><b>Rendimento</b></label>
                <input type="text" class="form-control" name="rendimento" placeholder="Ex. serve 1 pessoa"
                  value="{{ receita.rendimento }}" required />
              </div>
              <div class="col-12 col-lg-3">
                <label for="file"><b>Categoria da receita</b></label>
                <input type="text" class="form-control" name="categoria" placeholder="Ex. Sucos e bebidas"
                  value="{{ receita.categoria }}" required />
              </div>
              <div class="col-12 col-lg-3">
                <label for="file"><b>Foto</b></label>
                <input type="file" class="form-control" name="foto_receita" value="{{ receita.foto_receita }}" />
              </div>
              <div class="col-12 text-center">
                <button class="btn delicious-btn mt-30" type="submit">
                  Salvar
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% include 'partials/_footer.html' %} {% endblock %}

templates/usuarios/login.html
{% extends 'base.html' %} {% load static %} {% block content %}
<!-- Preloader -->
<div id="preloader">
  <i class="circle-preloader"></i>
  <img src="{% static 'img/core-img/pizza.png' %}" alt="" />
</div>

{% if messages %} {% for message in messages %}
<div id="liveAlertPlaceholder" class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
{% endfor %} {% endif %} {% include 'partials/_busca.html' %}
{% include 'partials/_menu.html' %}

<!-- ##### Contact Form Area Start ##### -->
<div class="contact-area section-padding-0-80">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="section-heading">
          <h2>Login</h2>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-12">
        <div class="contact-form-area">
          <form action="{% url 'login' %}" method="POST">
            {% csrf_token %}
            <div class="row">
              <div class="col-12 col-lg-12">
                <label for="email"><b>Email</b></label>
                <input type="text" id="email" class="form-control" name="email"
                  placeholder="Entre com o email cadastrado" required />
              </div>
              <div class="col-12 col-lg-12">
                <label for="senha"><b>Senha</b></label>
                <input id="senha" type="password" class="form-control" name="senha" placeholder="Digite aqui sua senha"
                  required />
              </div>
              <div class="col-12 text-center">
                <button class="btn btn-success" type="submit">
                  Acessar sua conta
                </button>
                <button type="button" class="btn btn-primary" onclick="exibirCriarConta()">
                  Ainda não tem conta? Clique aqui
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  function exibirCriarConta() {
    location.href = "{% url 'cadastro' %}";
  }
</script>

{% include 'partials/_footer.html' %} {% endblock %}