alurareceita/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("receitas.urls")),
    path("usuarios/", include("usuarios.urls")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/receitas/urls.py
from django.urls import path

from receitas import views

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:id_receita>", views.receitas, name="receita"),
    path("buscar", views.buscar, name="buscar"),
]

receitas/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from receitas import views

app_name = "receitas"
urlpatterns = [
    path("", views.index, name="index"),
    path("receitas/<int:id_receita>", views.detalhe, name="detalhe"),
    path("receitas/buscar", views.buscar, name="buscar"),
    path(
        "receitas/criar",
        login_required(views.CriaReceita.as_view(), login_url="login"),
        name="criar",
    ),
    path(
        "receitas/editar/<int:id_receita>",
        login_required(views.EditaReceita.as_view(), "login"),
        name="editar",
    ),
    path(
        "receitas/deletar/<int:id_receita>",
        login_required(views.DeletaReceita.as_view(), login_url="login"),
        name="deletar",
    ),
]

handler404 = "receitas.views.error404"

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="description" content="">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

  <!-- Título -->
  <title>Alura Receitas</title>

  <!-- Favicon -->
  <link rel="icon" href=" {% static 'img/core-img/favicon.ico' %} ">

  <!-- Stylesheet -->
  <link rel="stylesheet" type="text/css" href=" {% static 'site.css' %} ">

</head>

<body>
  {% block content %} {% endblock %}
  <!-- ##### All Javascript Files ##### -->
  <!-- jQuery-2.2.4 js -->
  <script src="{% static 'js/jquery/jquery-2.2.4.min.js' %}"></script>
  <!-- Popper js -->
  <script src="{% static 'js/bootstrap/popper.min.js' %}"></script>
  <!-- Bootstrap js -->
  <script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
  <!-- All Plugins js -->
  <script src="{% static 'js/plugins/plugins.js' %}"></script>
  <!-- Active js -->
  <script src="{% static 'js/active.js' %}"></script>
</body>

</html>

templates/buscar.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Preloader -->
<div id="preloader">
  <i class="circle-preloader"></i>
  <img src="{% static 'img/core-img/pizza.png' %}" alt="">
</div>

{% include 'partials/_busca.html' %}

{% include 'partials/_menu.html' %}

<!-- ##### Best Receipe Area Start ##### -->
<section class="best-receipe-area">
  <div class="container">
    <div class="row">
      {% if receitas %}
      {% for receita in receitas %}
      <!-- Single Best Receipe Area -->
      <div class="col-12 col-sm-6 col-lg-4">
        <div class="single-best-receipe-area mb-30">
          {% if not receita.foto_receita %}
          <img src="{% static 'img/bg-img/foto_receita.png' %}" width="350px" , height="352px" alt="">
          {% else %}
          <img src="{{ receita.foto_receita.url }}" style="width: 350px; height: 352px;" alt="">
          {% endif %}
          <div class="receipe-content">
            <a href="{% url 'receitas:receita' receita.id %}">
              <h5>{{receita.nome_receita}}</h5>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
      {% else %}
      <div class="col-12 col-sm-6 col-lg-4">
        <p>Receita não encontrada</p>
      </div>
      {% endif %}
    </div>
  </div>
</section>
<!-- ##### Best Receipe Area End ##### -->
{% include 'partials/_footer.html' %}
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Preloader -->
<div id="preloader">
  <i class="circle-preloader"></i>
  <img src="{% static 'img/core-img/pizza.png' %}" alt="">
</div>

{% include 'partials/_busca.html' %}

{% include 'partials/_menu.html' %}

<!-- ##### Best Receipe Area Start ##### -->
<section class="best-receipe-area">
  <div class="container">
    <div class="row">
      {% if receitas %}
      {% for receita in receitas %}
      <!-- Single Best Receipe Area -->
      <div class="col-12 col-sm-6 col-lg-4">
        <div class="single-best-receipe-area mb-30">
          {% if not receita.foto_receita %}
          <img src="{% static 'img/bg-img/foto_receita.png' %}" alt="">
          {% else %}
          <img src="{{ receita.foto_receita.url }}" alt="">
          {% endif %}
          <div class="receipe-content">
            <a href="{% url 'receitas:detalhe' receita.id %}">
              <h5>{{receita.nome_receita}}</h5>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
      {% else %}
      <div class="col-12 col-sm-6 col-lg-4">
        <p>Nenhuma receita encontrada</p>
      </div>
      {% endif %}
    </div>
</section>
<!-- ##### Pagination ##### -->
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {% if receitas.has_other_pages %}
    {% if receitas.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ receitas.previous_page_number }}"><span aria-hidden="true">&laquo;</span></a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="?page={{ page. }}"> <span aria-hidden="true">&laquo;</span> </a>
    </li>
    {% endif %}

    {% for page in receitas.paginator.page_range %}
    {% if page == receitas.number %}
    <li class="page-item active">
      <a class="page-link" href="?page={{ page }}">{{ page }}</a>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page }}">{{ page }}</a>
    </li>
    {% endif %}
    {% endfor %}

    {% if not receitas.has_next %}
    <li class="page-item disabled">
      <a class="page-link"><span aria-hidden="true">&raquo;</span></a>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ receitas.next_page_number }}"> <span aria-hidden="true">&raquo;</span> </a>
    </li>
    {% endif %}
    {% endif %}
  </ul>
</nav>
<!-- ##### Pagination End ##### -->
</div>
<!-- ##### Best Receipe Area End ##### -->
{% include 'partials/_footer.html' %}
{% endblock %}